# Generated by Django 4.2.1 on 2023-06-05 07:51

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Commentary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(blank=True, null=True)),
                ("created_time", models.DateTimeField(auto_now_add=True)),
                (
                    "commentary_image",
                    models.ImageField(
                        blank=True, upload_to="media/commentaries_image/"
                    ),
                ),
            ],
            options={
                "ordering": ["created_time"],
            },
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField(blank=True, null=True)),
                ("created_time", models.DateTimeField(auto_now_add=True)),
                (
                    "post_image",
                    models.ImageField(blank=True, upload_to="media/posts_image/"),
                ),
            ],
            options={
                "ordering": ["created_time"],
            },
        ),
    ]
