# Generated by Django 4.2.1 on 2023-06-05 08:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("post_service", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(blank=True, max_length=255, null=True)
                ),
                ("bio", models.TextField(blank=True, max_length=500)),
                ("birth_date", models.DateField(blank=True, null=True)),
                (
                    "location",
                    models.CharField(blank=True, max_length=100, null=True)
                ),
                (
                    "picture",
                    models.ImageField(blank=True, upload_to="media/profile_pictures/"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
        ),
    ]
