# Generated by Django 4.2.1 on 2023-06-07 07:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("post_service", "0003_userprofile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="post_image",
            field=models.ImageField(blank=True, upload_to="media/post_image/"),
        ),
    ]
