# Generated by Django 4.2.1 on 2023-06-13 10:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("post_service", "0004_alter_post_post_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="owner",
            new_name="user",
        ),
    ]
