# Generated by Django 4.2.1 on 2023-06-15 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("post_service", "0005_rename_owner_post_user"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userprofile",
            options={"ordering": ["name"]},
        ),
        migrations.AddField(
            model_name="userprofile",
            name="post",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="posts",
                to="post_service.post",
            ),
        ),
    ]
