# Generated by Django 4.2.1 on 2023-06-16 11:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("post_service", "0009_upvote"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="upvote_count",
            field=models.IntegerField(default=0),
        ),
    ]
