# Generated by Django 4.2.1 on 2023-06-16 11:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("post_service", "0010_post_upvote_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="upvote",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="upvotes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
