# Generated by Django 4.2.1 on 2023-06-18 13:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("post_service", "0011_alter_upvote_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userprofile",
            old_name="my_followers",
            new_name="followers",
        ),
        migrations.RenameField(
            model_name="userprofile",
            old_name="i_follow",
            new_name="following",
        ),
    ]
