# Generated by Django 4.2.1 on 2023-06-18 13:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("post_service", "0013_userfollowing_userfollowing_unique_following"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="posts",
            field=models.ManyToManyField(
                related_name="posts",
                to="post_service.post"
            ),
        ),
    ]
