# Generated by Django 4.2.1 on 2023-06-18 13:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("post_service", "0014_userprofile_posts"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="userfollowing",
            name="unique_following",
        ),
        migrations.RenameField(
            model_name="userfollowing",
            old_name="user_id",
            new_name="email_id",
        ),
        migrations.RenameField(
            model_name="userfollowing",
            old_name="following_user_id",
            new_name="following_email_id",
        ),
        migrations.AddConstraint(
            model_name="userfollowing",
            constraint=models.UniqueConstraint(
                fields=(
                    "email_id",
                    "following_email_id"
                ),
                name="unique_following"
            ),
        ),
    ]
