# Generated by Django 4.2.1 on 2023-06-18 14:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "post_service",
            "0015_remove_userfollowing_unique_following_and_more"
        ),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="userfollowing",
            name="unique_following",
        ),
    ]
