# Generated by Django 4.2.1 on 2023-06-19 16:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "post_service",
            "0016_remove_userfollowing_unique_following_and_more"
        ),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserFollowing",
        ),
    ]
